[package]
name = "bevy_ecs_ldtk"
description = "An ECS-friendly ldtk plugin for bevy."
version = "0.1.0"
edition = "2021"
authors = ["Trevor Lovell <trevorlovelldesign@gmail.com>"]
repository = "https://github.com/Trouv/bevy_ecs_ldtk"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "ldtk", "game", "gamedev", "map-editor"]
categories = ["Game development"]
exclude = ["assets/*", "repo/*", "scripts/*"]

[dependencies]
bevy_ecs_ldtk_macros = { version = "0.1", optional = true, path = "macros" }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "bevy-track" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"

[features]
default = ["app", "derive"]
app = []
derive = ["bevy_ecs_ldtk_macros", "app"]
