[package]
name = "bevy_ecs_ldtk"
version = "0.1.0"
authors = ["Trevor Lovell <trevorlovelldesign@gmail.com>"]
edition = "2021"

[dependencies]
bevy_ecs_ldtk_derive = { version = "0.1", optional = true, path = "derive" }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap", branch = "bevy-track" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"

[features]
derive = ["bevy_ecs_ldtk_derive"]
